/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Adventurer": "冒险者",
    "log": "日志",
    "Lv Up!": "升级了！",
    "menu": "菜单",
    "pause": "暂停",
    "Upper Coast": "上海岸",
    "Up to 30 minutes of away time is automated. After that, up to 8 hours is banked and allows you to run the game at double speed.": "长达 30 分钟的离开时间是自动化的。 之后，最多可存储 8 小时，并允许您以双倍速度运行游戏。",
    "Water Serpent": "水蛇",
    "AGI": "敏捷",
    "Auto Progress": "自动进度",
    "Ballad of a Champion": "冠军之歌",
    "Ballads": "歌谣",
    "'s attack hits": "的攻击命中",
    "attacks": "攻击",
    "Ballad of Heroes": "英雄之歌",
    "Critical hit!": "暴击！",
    "patreon": "赞助",
    "The enemy party has been defeated.": "敌方已被击败。",
    "uses Quick Hit on": "使用快速攻击",
    "uses Thousand Cuts.": "使用千刃斩。",
    "Your party gains": "你的队伍获得了",
    "Agility:": "敏捷：",
    "Average": "平均",
    "Coins:": "金币：",
    "Auto Attack": "自动攻击",
    "Attack Speed:": "攻击速度：",
    "Attack:": "攻击：",
    "Crustacean": "甲壳动物",
    "damage after each auto attack or ability. 60 second cooldown.": "每次自动攻击或技能后造成的伤害。 60 秒冷却时间。",
    "damage and increase Agility by": "伤害并增加敏捷",
    "Deal": "造成",
    "Defense:": "防御：",
    "Luck:": "幸运：",
    "Max HP:": "生命上限：",
    "No abilities.": "没有能力。",
    "No loot.": "没有战利品。",
    "Quick Hit": "快速攻击",
    "Resistance:": "抵抗：",
    "Right click to toggle between Manual and Auto mode. Left click or press": "右键点击可在手动和自动模式之间切换。 左键单击或按下",
    "seconds, deal an additional": "秒，造成一个额外的",
    "seconds.": "秒。",
    "Thousand Cuts": "千刃斩",
    "Throwing Stone": "飞石",
    "to use ability in Manual mode.": "在手动模式下使用能力。",
    "uses Overdrive: Smash.": "使用超频：粉碎。",
    "XP:": "经验：",
    "You move to": "你移动到了",
    "Jump to..": "跳转到..",
    "Ballad of the Gorgon": "蛇发女妖之歌",
    "General": "常规",
    "Latest Town": "最新城镇",
    "View Followers": "查看追随者",
    "damage.": "伤害。",
    "damage. Heal for": "伤害。造成",
    "Divine Strike": "神圣一击",
    "Holy": "神圣",
    "'s overdrive ends.": "的超频结束。",
    "activate": "激活",
    "Achievement Unlocked": "成就解锁",
    "battle": "战斗",
    "As you proceed on your journey, you will have access to different altars to honor the gods. Select the Altar on the right and pray to Athena to gain a party-wide buff and affinity EXP for Athena.": "当您继续您的旅程时，您将可以访问不同的祭坛来纪念众神。 选择右边的祭坛，向雅典娜祈祷，可以获得全队BUFF和雅典娜亲和力经验。",
    "Thief": "窃贼",
    "Highwayman": "拦路强盗",
    "attains level": "达到等级",
    "Bandit": "土匪",
    "Battle Rewards": "战斗奖励",
    "Battle State Updates": "战斗状态更新",
    "Buy": "购买",
    "Character Level Up": "角色升级",
    "Delphi Outskirts": "德尔福郊区",
    "Each follower provides a 2% chance per minute to pray to a random god's Small Altar and receive a boon for the party. This does not require an altar to be activated. You cannot receive the same exact boon more than once at a time.": "每个追随者每分钟有 2% 的机会向随机神灵的小祭坛祈祷并为队伍获得恩赐。 这不需要激活祭坛。 您不能一次多次获得完全相同的恩赐。",
    "Each follower provides a 25% chance per minute to activate any Small Altar among your three available altars that have met their necessary activation conditions.": "每个追随者每分钟有 25% 的机会激活您三个满足必要激活条件的可用祭坛中的任何一个小祭坛。",
    "Enemy Ability Use": "敌人技能使用",
    "Enemy Auto Attacks": "敌人自动攻击",
    "Enemy Status Effect Updates": "敌人状态效果更新",
    "Equipment Effect Updates": "装备效果更新",
    "Follower Prayer": "追随者祈祷",
    "Follower Search": "追随者搜索",
    "for a new follower.": "对于一个新的追随者。",
    "Found Treasure Chest": "发现宝箱",
    "gains": "收益",
    "Game Log Editor": "游戏日志编辑器",
    "God Level Up": "神明升级",
    "Heal a party member for 50 HP.": "治疗一名队员 50 生命值。",
    "Healing Herb": "药草",
    "misc": "杂项",
    "new followers": "新的追随者",
    "No followers are currently praying.": "目前没有追随者在祈祷。",
    "No followers are currently searching.": "当前没有追随者正在搜索。",
    "Overview": "概览",
    "Party Ability Use": "队伍能力使用",
    "Party Auto Attacks": "队伍自动攻击",
    "Party Overdrives": "队伍超频",
    "Party Status Effect Updates": "队伍状态效果更新",
    "pray": "祈祷",
    "Pray To Altar": "祈祷祭坛",
    "prayer": "祈祷者",
    "Prayer": "祈祷者",
    "Purchase": "购买",
    "search": "搜索",
    "Search": "搜索",
    "Small Altars": "小祭坛",
    "The story of your accomplishments has spread all throughout Greece. Some people have taken to follow you and are able to assist you in various ways.": "您的成就传遍了整个希腊。 有些人已经开始追随你，并能够以各种方式帮助你。",
    "Unassign All": "全部取消分配",
    "Use Battle Item": "使用战斗道具",
    "uses Divine Strike on": "对",
    "v0.42 beta": "v0.42 测试版",
    "while searching Aigosthena.": "在寻找 Aigosthena 的时候。",
    "You can assign a follower to any zone that you have cleared. Gaining achievements in a zone will increase the level of that zone, increasing the yield your followers may find.": "您可以将追随者分配到您已清除的任何区域。 在某个区域获得成就会提高该区域的等级，从而增加您的追随者可能获得的收益。",
    "You can assign a follower to pray to the gods for your success.": "您可以指派一名追随者为您的成功向众神祈祷。",
    "You gain": "你获得",
    "You receive": "你收到",
    "Your followers found": "找到您的追随者",
    "Your party has been defeated. You hurry back to the safety of town.": "你的队伍被打败了。 你赶紧回到安全的城镇。",
    "All": "全部",
    "All Items": "所有物品",
    "Armor": "盔甲",
    "Battle Items": "战斗物品",
    "Equipment": "装备",
    "Equippable Healing Item": "可装备治疗物品",
    "Iron Armor": "铁甲",
    "Iron Hammer": "铁锤",
    "Iron Shield": "铁盾",
    "Iron Sword": "铁剑",
    "Linen Armor": "亚麻盔甲",
    "New Items": "新物品",
    "Shield": "盾牌",
    "Short Bow": "短弓",
    "Show:": "显示：",
    "Unequipped": "未装备",
    "Bow": "弓",
    "Hammer": "锤子",
    "Sword": "剑",
    "Countryside": "乡村",
    "on his journey to defeat the monstrous Medusa. As you cross the countryside between Locris and Aetolia, you get the feeling you are being followed. You've battled numerous bandits on your path and before this one can get the jump on you, you go on the offensive.": "在他击败可怕的美杜莎的旅程中。 当您穿过 洛克里斯 和 埃托利亚 之间的乡村时，您会感到自己被跟踪了。 你在路上与无数强盗作战，在这个强盗抢到你之前，你继续进攻。",
    " Heal for": "治愈",
    ", the triumph and fall of": ", 的胜利与陨落",
    ", the winding journey of": ", 曲折的旅程",
    ". Could you truly be in the same conversations as these heroes?": ". 你真的能和这些英雄进行同样的对话吗？",
    ". Could you walk the path of champions? You know all of the stories by heart -- the trials of": ". 能否走上冠军之路？ 你对所有的故事都了如指掌——",
    ". View passive ability description by hovering your god's name.": ". 将鼠标悬停在你神的名字上，查看被动能力描述。",
    "1 follower is  searching Aigosthena for 3 Light Leathers.": "1 位追随者搜索 Aigosthena 时找到了 3 轻型皮革。",
    "Click or press": "单击或按下",
    "Coastal Roads of Locris": "洛克里斯 的沿海道路",
    "gains 3 HP from Second Wind.": "从复苏之风中获得 3 点生命值。",
    "Heracles": "赫拉克勒斯",
    "Increase Agility by 25%.": "敏捷提高 25%。",
    "Jason": "杰森",
    "learns a new  passive  ability:": "学习一个新的被动技能：",
    "Odysseus": "奥德修斯",
    "Perseus": "英仙座",
    "Coastal Roads of Locris": "洛克里斯 的沿海道路",
    "Countryside": "乡村",
    "Second Wind": "复苏之风",
    "See a brief overview of important resources and quick links to important locations.": "查看重要资源的简要概述和重要位置的快速链接。",
    "to toggle targeting mode. After activating, click an enemy to target all auto attacks and abilities from this character on that enemy.": "切换定位模式。 激活后，单击一个敌人可以将该角色的所有自动攻击和技能都瞄准该敌人。",
    "uses Healing Herb, gaining 50 HP.": "使用治疗草药，获得 50 生命值。",
    "You find your way out of Delphi while processing your meeting with": "您在处理与 德尔福 的会议时找到了离开 德尔福 的方法",
    "Your feet unconsciously make their way northwest towards Dodona, following the path of": "你的脚不自觉地向西北走向多多纳，沿着",
    "Archer": "弓箭手",
    "Red-Feathered Harpy": "红羽鹰身女妖",
    ", but you feel this Archer matches you in the same way. As your fight comes to a stalemate, you raise your hands in surrender.": "，但你觉得这个弓箭手和你一样匹配。 当你的战斗陷入僵局时，你举起双手投降。",
    ". The goddess": ". 女神",
    "“I didn't mean to startle you.”": "“我不是故意吓到你的。”",
    "“I thought you were trying to mug me, but you fight harder than an ordinary bandit. Why are you following me?”": "“我还以为你是来抢劫我的呢，没想到你比普通的强盗还厉害。 你为什么跟着我？”",
    "“I was leaving Delphi at the same time as you, and couldn't help notice you cutting down the outlaws running these roads. Following you made it easier to travel.. and I was curious what you were after.”": "“我和你同时离开德尔福，不禁注意到你砍掉了这些道路上的不法分子。 跟着你让旅行变得更容易……我很好奇你在追求什么。”",
    "“If you want a challenge, then walk with me to Dodona.": "“如果你想要挑战，那就和我一起去多多纳。",
    "“My name is": "“我的名字是",
    "“Sorry about that.”": "“对于那个很抱歉。”",
    "1 to all other primary stats": "1 到所有其他主要属性数据",
    "Air": "空气",
    "and": "和",
    "Archer": "射手",
    "Artemis": "阿尔忒弥斯",
    "ATK": "攻击",
    "Blue-Feathered Harpy": "蓝羽鹰身女妖",
    "Coyote": "土狼",
    "guides my arrows. She tasked me with hunting the strongest enemies I can find to prove myself worthy of defending Olympus. I almost added you to that list.”": "指引我的箭。 她指派我去猎杀我能找到的最强大的敌人，以证明我有资格保卫奥林匹斯山。 我差点把你加入那个名单。”",
    "guides my path as": "指引我的道路",
    "guides yours. Keep your distance if you choose, but we have the same goal. We can prove ourselves together.”": "指导你的。 如果你选择保持距离，但我们有相同的目标。 我们可以一起证明自己。”",
    "learns a new  ability:": "学习一项新能力：",
    "Road to Dodona - Mountain Opening": "通往多多纳的道路 - 开放的山口",
    "Sure Shot": "必杀技",
    "takes 3 damage from Sure Shot's effect.": "受到 必杀技 效果的 3 点伤害。",
    "takes 5 damage from Claw's effect.": "受到爪击效果的 5 点伤害。",
    "takes 5 damage from Sure Shot's effect.": "受到 必杀技 效果的 5 点伤害。",
    "The gods seem to each have their own favorites.": "诸神似乎各有各的喜好。",
    "Throwing Stones": "投掷石块",
    "uses Claw on": "使用爪",
    "uses Enrage.": "使用激怒。",
    "uses Sure Shot on": "使用 必杀技",
    "uses Wounding Arrow on": "使用致伤箭",
    "You find a treasure chest containing": "你找到一个宝箱，里面有",
    "You reply with a grin.": "你笑着回答。",
    "Your opponent says, cautiously lowering her bow.": "你的对手说，小心地放下她的弓。",
    "Your power has grown significantly since you were chosen by": "自从被选为",
    "Zosime": "佐西美",
    "Heart of the Woods": "树林之心",
    "Divine Strike Upgrade 1": "神圣打击升级 1",
    "Second Wind Upgrade 1": "第二次风升级 1",
    "True Shot Upgrade 1": "真枪实弹升级 1",
    "Wounding Arrow Upgrade 1": "致伤箭升级 1",
    ". Passive.": ". 被动的。",
    "(Can obtain 10 more times)": "(可再获得10次)",
    "+1 Large Charm of Air Protection": "+1 大空气防护符咒",
    "+1 Large Charm of Determination": "+1 大决心护符",
    "+1 Large Charm of Holy Destruction": "+1 大型神圣毁灭符咒",
    "+1 Large Charm of Lightning Destruction": "+1 大号闪电毁灭符咒",
    "+1 Small Charm of Air Destruction": "+1 空气毁灭小符咒",
    "+1 Small Charm of Air Protection": "+1 小护身符",
    "+1 Small Charm of Earth Destruction": "+1 小地球毁灭符咒",
    "+1 Small Charm of Earth Protection": "+1 大地保护小符咒",
    "+1 Small Charm of Holy Destruction": "+1 神圣毁灭小符咒",
    "+1 Small Charm of Lightning Destruction": "+1 闪电毁灭小符咒",
    "+1 Small Charm of Rejuvenation": "+1 小护身符",
    "+1 Small Charm of Vulnerability": "+1 脆弱护符",
    "+1 Small Charm of Water Destruction": "+1 小型水毁符咒",
    "+1 Small Charm of Water Protection": "+1 小型防水护身符",
    "Abilities": "能力",
    "Affinity": "亲和力",
    "After using an ability, your next auto attack heals for": "使用技能后，你的下一次自动攻击会治疗",
    "Aigosthena - Heart of the Woods": "Aigosthena - 森林之心",
    "Aigosthena - Lower Coast": "Aigosthena - 下海岸",
    "Aigosthena - Western Woodlands": "Aigosthena - 西部林地",
    "Armor:": "盔甲：",
    "Artemis, Goddess of the Hunt, focuses on critical hits and debilitating enemies. Her abilities and upgrades can weaken enemies through status effects and increase damage dealt from critical attacks.": "狩猎女神阿尔忒弥斯专注于重击和削弱敌人。 她的能力和升级可以通过状态效果削弱敌人，并增加关键攻击造成的伤害。",
    "Athena, Goddess of Wisdom and Warfare, focuses on combat and self-reliance. Her abilities and upgrades give the user the ability to heal themselves based on damage dealt and reduce incoming damage to themselves.": "智慧和战争女神雅典娜专注于战斗和自力更生。 她的能力和升级使用户能够根据造成的伤害来治愈自己，并减少对自己造成的伤害。",
    "auto attack hits all additional enemies for": "自动攻击击中所有额外的敌人",
    "Ballad:": "歌谣：",
    "Barrage": "火力网",
    "Boon of Olympus:": "奥林匹斯的恩赐：",
    "Can be found at:": "可以在以下位置找到：",
    "Change": "改变",
    "Change Equipment": "换装备",
    "Change Gods": "更换神明",
    "Change Overdrive": "改变超频",
    "Character Abilities": "角色能力",
    "Charms": "护身符",
    "Classes": "职业",
    "Click for details on God.": "点击查看大神详情。",
    "coins": "金币",
    "Critical Damage Bonus:": "暴击伤害加成：",
    "Currently assigned to:": "目前分配给：",
    "damage to a target and reduce their attack by": "对目标造成伤害并减少他们的攻击",
    "Equipped God Abilities": "装备神能力",
    "Every": "每一个",
    "For 20 seconds, your auto attacks deal 25% increased damage.": "在 20 秒内，你的自动攻击造成的伤害提高 25%。",
    "Gods": "神明",
    "Healing Herbs:": "治疗草药：",
    "Heavenly Shield (Ability 2)": "天堂之盾（能力 2）",
    "HP Regen:": "生命恢复：",
    "HP. Passive.": "生命值。 被动的。",
    "Increase all characters' Holy damage by": "增加所有角色的神圣伤害",
    "Increase all characters' HP Regen by": "增加所有角色的 HP Regen",
    "Increase Base Prayer Duration by 50%": "基础祈祷持续时间增加 50%",
    "Increase experience gained by all gods.": "增加所有神获得的经验。",
    "Iron Sword:": "铁剑：",
    "Leathers:": "皮革：",
    "Light Leathers:": "轻型皮革：",
    "Mark": "标记",
    "Necklace:": "项链：",
    "Next Reward:": "下一个奖励：",
    "No God Assigned": "没有神明指派",
    "of the damage dealt every 3 seconds for": "每 3 秒造成的伤害",
    "of the damage dealt. Passive.": "造成的伤害。 被动的。",
    "Olives:": "橄榄：",
    "Overdrives": "超频",
    "Page:": "页：",
    "Paralyzing Volley (Ability 2)": "麻痹齐射（二技能）",
    "Patriarch": "族长",
    "per page": "每页",
    "Primary Stat Bonuses": "主要属性加成",
    "Primary Stats": "主要属性数据",
    "Progression": "进展",
    "Resources": "资源",
    "Resources & Crafting Materials": "资源和工艺材料",
    "Ring:": "戒指：",
    "Secondary Stat Bonuses": "次要属性加成",
    "Secondary Stats": "次要统计",
    "Select": "选择",
    "Sell": "出售",
    "Set New Overdrive": "设置新的超频",
    "Shield:": "护盾：",
    "Show Uncompleted Only": "仅显示未完成",
    "Small Charm of Rejuvenation:": "回春小符咒：",
    "Smash": "粉碎",
    "Smash (Overdrive)": "粉碎（超频）",
    "Subzone:": "子区域：",
    "Swap": "互换",
    "Throwing Stones:": "投掷石块：",
    "Total Overdrive Points Required: 80": "所需的总超频点数：80",
    "tracking": "追踪",
    "True Shot (Passive Ability)": "真实射击（被动能力）",
    "Unlock: Deal 250,000 elemental damage.": "解锁：造成 250,000 元素伤害。",
    "Unlock: Reach character level 20.": "解锁：达到角色等级 20。",
    "Unlock: Take 100,000 damage.": "解锁：受到100,000点伤害。",
    "Upcoming Level Rewards": "即将到来的等级奖励",
    "Use to trade with merchants.": "用于与商人交易。",
    "Used for crafting.": "用于制作。",
    "Waxes:": "蜡：",
    "Weapon:": "武器：",
    "When an enemy has a status effect that you have applied, they also have Mark. Mark increases damage taken by": "当敌人有你应用的状态效果时，他们也会有标记。 标记增加受到的伤害",
    "Wounding Arrow": "致伤箭",
    "Zone:": "区域：",
    "LCK": "幸运",
    "uses Empower.": "使用 赋能。",
    "Empower": "赋能",
    "True Shot": "必杀技",
    "Damage Per Second is calculated over a 120 second period and is reset upon changing sub zones.": "每秒伤害是在 120 秒的时间内计算的，并在更改子区域时重置。",
    "If your target has a negative status effect, increase critical strike chance by": "如果你的目标有负面状态效果，增加致命一击几率",
    "See available altars to pray for boons.": "查看可用的祭坛以祈求恩赐。",
    "Thales is assigned to the Adventurer class. Click for details on class.": "泰利斯被分配到冒险者职业。 点击了解职业详情。",
    "when attacking. Passive.": "攻击的时候。 被动的。",
    "Zosime is assigned to the Archer class. Click for details on class.": "佐西美 被分配到 弓箭手 职业。 点击了解课程详情。",
    "uses Ravage on": "使用毁灭在",
    "4th": "第4",
    "Poison Fangs:": "毒牙：",
    "Code Redemption": "代码兑换",
    "Code:": "代码：",
    "Dark": "深色",
    "Enter": "确认",
    "Export to File": "导出为文件",
    "Fast": "快",
    "Import from File": "从文件导入",
    "Light": "浅色",
    "Medium": "中",
    "Pause": "暂停",
    "Save/Load": "保存/加载",
    "Show Enemy HP As Percent": "以百分比显示敌人生命值",
    "Show Party HP As Percent": "以百分比显示队伍生命值",
    "Skip": "跳过",
    "Slow": "慢",
    "story speed": "故事速度",
    "tooltip color theme": "工具提示颜色主题",
    "Update Keybinds": "更新快捷键",
    "Update Quick View Options": "更新快速查看选项",
    ". It is modest compared to the one in Athens, but it is the largest most people in your village will ever see. From generation to generation, the story has held that the first person to reach the temple on the day of the Festival will be graced with the presence of": ". 与雅典的相比，它的规模不大，但它是你们村里大多数人见过的最大的。 世代相传，节日当天第一个到达寺庙的人将受到",
    "Click the arrow button to the right to skip to the next page": "点击右边的箭头按钮跳到下一页",
    "damage to a single target 1.000 time every": "伤害对单个目标造成 1.000 次每次",
    "Every year, you and many others set out inland to the Temple of": "每年，你和许多其他人都会前往内陆前往圣殿",
    "herself.": "她自己。",
    "in their own way. You race simply because every year you have tried, and every year you have failed. You have always yearned for greatness, but could never quite reach it. This year was going to be different.": "以他们自己的方式。 你参加比赛只是因为每一年你都尝试过，每一年你都失败了。 你一直渴望伟大，但永远无法实现。 今年会有所不同。",
    "of Aigosthena, are racing.": "Aigosthena，正在赛车。",
    "Some believe the stories and race to prove their piety. Others race to prove their skill and honor": "有些人相信这些故事并竞相证明他们的虔诚。 其他人竞相证明自己的技能和荣誉",
    "Thales": "泰雷兹",
    "Today is the Festival of Gods in your small village in Greece. Musicians are performing, children are playing, men and women are eating and drinking.": "今天是希腊小村庄的众神节。 音乐家在表演，孩子们在玩耍，男人和女人在吃喝。",
    "You automatically attack opponents over time. Hover over the sword by your character's name for more details.": "随着时间的推移，你会自动攻击对手。 将鼠标悬停在您角色名称旁边的剑上以获取更多详细信息。",
    "You": "你",
    "You received your first battle item. Click the plus sign on the bottom left to add an item to your item belt and click the item again to use it. Some items require you to click an ally or enemy to use. Hover over an item to see its effect.": "你收到了你的第一个战斗物品。 单击左下角的加号将一个项目添加到您的项目腰带，然后再次单击该项目以使用它。 有些物品需要你点击一个盟友或敌人才能使用。 将鼠标悬停在项目上以查看其效果。",
    "You've won enough battles here to move to the next area. On the right side of the screen, select 'Bay' to move to the next subzone within the 'Aigosthena' zone. If you wish, you can select 'Auto Progress' at the top of the page to automatically move to the next subzone when possible.": "你在这里赢得了足够多的战斗，可以移动到下一个区域。 在屏幕右侧，选择“海岸”以移动到“Aigosthena”区域内的下一个子区域。 如果您愿意，您可以选择页面顶部的“自动进度”，以便在可能的情况下自动移动到下一个子区域。",
    "Date Received": "收到日期",
    "Every year, you and many others set out inland to the Temple of": "每年，你和许多其他人都会前往内陆前往圣殿",
    "herself.": "她自己。",
    "in their own way. You race simply because every year you have tried, and every year you have failed. You have always yearned for greatness, but could never quite reach it. This year was going to be different.": "以他们自己的方式。 你参加比赛只是因为每一年你都尝试过，每一年你都失败了。 你一直渴望伟大，但永远无法实现。 今年会有所不同。",
    "Info": "信息",
    "Loot": "战利品",
    "of Aigosthena, are racing.": "Aigosthena，正在赛车。",
    "Some believe the stories and race to prove their piety. Others race to prove their skill and honor": "有些人相信这些故事并竞相证明他们的虔诚。 其他人竞相证明自己的技能和荣誉",
    "Story": "故事",
    "Thales": "泰雷兹",
    "Today is the Festival of Gods in your small village in Greece. Musicians are performing, children are playing, men and women are eating and drinking.": "今天是希腊小村庄的众神节。 音乐家在表演，孩子们在玩耍，男人和女人在吃喝。",
    "Tutorials": "教程",
    "You automatically attack opponents over time. Hover over the sword by your character's name for more details.": "随着时间的推移，你会自动攻击对手。 将鼠标悬停在您角色名称旁边的剑上以获取更多详细信息。",
    "You received 15 Throwing Stone.": "你收到了 15 个投掷石。",
    "You,": "你，",
    "uses Constrict.": "使用 挤压。",
    "Constrict": "挤压",
    "Crafter": "工匠",
    "uses Gaze.": "使用凝视。",
    "Fortified Bronze Armor": "强化青铜盔甲",
    "Fortified Bronze Hammer": "强化青铜锤子",
    "Fortified Bronze Sword": "强化青铜剑",
    "Gaze": "凝视",
    "Venomstrike": "毒液打击",
    "Wax": "蜡",
    "uses Ethereal.": "使用空灵。",
    "Ethereal": "空灵",
    "'s attack misses!": "的攻击未命中！",
    " Hearts:": "之心：",
    "Aegis": "宙斯盾",
    "Aegis:": "宙斯盾：",
    "Always Active:": "始终活跃：",
    "play": "继续",
    "The amount of banked time you've gained while away from the game. While this is available, the game will run at 2x the speed. Click to toggle on or off.": "您离开游戏时获得的累积时间。 虽然这是可用的，但游戏将以 2 倍的速度运行。 单击以打开或关闭。",
    "The game is paused. Click or press the": "游戏已暂停。 点击或按",
    "The game is playing. Click or press the": "游戏已恢复。 点击或按",
    "key to pause.": "键去暂停游戏。",
    "key to unpause.": "键去恢复游戏。",
    "for a boon.": "恩赐。",
    "See all tracked resources. To track a specific resource, go to the 'Resources' tab in the menu and click an item.": "查看所有跟踪的资源。 要跟踪特定资源，请转到菜单中的“资源”选项卡并单击一个项目。",
    "Small Altar": "小祭坛",
    "to": "去",
    "to pray at a": "去祈祷在",
    "When the condition is met, click or press": "当满足条件时，点击或按下",
    "'s Thorns effect.": "的荆棘效果。",
    "Thorns": "荆棘",
    "Avoid all auto attacks.": "躲避所有自动攻击。",
    "damage from": "伤害从",
    "Dealing damage back to auto attackers.": "将伤害返还给自动攻击者。",
    "Resolves Upon Effect Condition": "根据效果条件解决",
    "takes": "受到",
    "'s ability": "的能力",
    "While you pass through, you hear the sound of wind moving rapidly behind you. You dodge out of the way just in time to avoid being ripped to shreds by a large figure. The owner of the nest isn't pleased to see you here. You will have to defeat this oversized bird to continue.": "当你经过时，你听到身后快速移动的风声。 你及时躲开，避免被一个大人物撕成碎片。 巢的主人不高兴在这里见到你。 你必须打败这只超大的鸟才能继续。",
    "And then she was gone. All that remained was the overwhelming smell of incense. After taking in what just occurred, you offer up another prayer and step back outside of the temple. But instead of woodlands, you see the open road. Instead of Aigosthena, you are in Delphi.": "然后她就走了。 只剩下铺天盖地的熏香。 在接受了刚刚发生的事情之后，你又做了一次祈祷，然后退到寺庙外面。 但是您看到的不是林地，而是开阔的道路。 你不是在 Aigosthena，而是在 德尔福。",
    ", but to you they are quiet. As you make your way around the grove, a youthful man wearing a feather-brimmed hat steps out to greet you.": "，但对你来说他们很安静。 当你绕着树林走时，一个戴着羽毛边帽的年轻人走出来迎接你。",
    "“Am I the first?”": "“我是第一个吗？”",
    "“Be warned, mortal, for my mother has foreseen the impending fall of Olympus. She sees the Giants and Titans joining forces and planning a coordinated attack against us. We cannot hope to stand against both of them on our own.": "“小心点，凡人，因为我的母亲已经预见到奥林匹斯山即将陷落。 她看到巨人和泰坦联合起来并计划对我们发动协同攻击。 我们不能指望凭一己之力对抗他们两者。",
    "“I... just wanted to follow in the footsteps of a real hero.”": "“我……只是想追随真正英雄的脚步。”",
    "“Sounds like we're heading to Libya.”": "“听起来我们要去利比亚。”",
    "“Take these too. They'll take you straight where you need to be.”": "“把这些也拿去。 他们会直接把你带到你需要去的地方。”",
    "“That's well and good, but we need a real hero of our own. Use those sandals and see if you have what it takes to defeat Medusa. I've got another pair for your friend there hiding in the shadows as well. Good luck!”": "“这很好，但我们需要一个真正的英雄。 使用那些凉鞋，看看你是否有能力打败美杜莎。 我还为你的朋友买了另一双，也藏在阴影里。 祝你好运！”",
    "“The next step on your journey is to slay Medusa. We're here to help you.”": "“你旅程的下一步是杀死美杜莎。 我们是来帮你的。”",
    "“This is your champion? Seems a little… fresh, don't you think?”": "“这是你的冠军？ 好像有点……新鲜，你不觉得吗？”",
    "“We must all start somewhere, brother.”": "“我们都必须从某个地方开始，兄弟。”",
    "“We will see you soon. Farewell.”": "“我们很快就会见到你。 告别。”",
    "“You are.”": "“你是。”",
    "“You know, I wasn't sure you would come all the way here. You know how the story went right? Medusa is in Libya. Just wanted to do some sightseeing?”": "“你知道，我不确定你会大老远地来这里。 你知道这个故事是怎么回事吗？ 美杜莎在利比亚。 只是想观光一下吗？”",
    "“You've done well. But your real trial is only just beginning.”": "“你做得很好。 但你真正的考验才刚刚开始。”",
    "“Your resolve is impressive.”": "“你的决心令人印象深刻。”",
    "a voice says from behind. The Goddess of Wisdom and Warfare.": "一个声音从背后说。 智慧与战争女神。",
    "As your thoughts stray, you belatedly notice you have stumbled into what looks like a bird nest. Overgrown eggs litter the sides of a massive roost.": "当你的思绪飘散时，你才发现自己跌跌撞撞地走进了一个看起来像鸟巢的地方。 长得太大的鸡蛋散落在一个巨大的栖息地的两侧。",
    "before you, you wander through the oak grove outside of Dodona. The stories say that the trees spoke advice to": "在您之前，您漫步在多多纳 (Dodona) 外的橡树林中。 故事说树木向",
    "can look into the eyes of a ten foot tall half-man with the head of a snarling bull, then what do you have to fear?": "能直视一个十英尺高的半人，长着一头咆哮的公牛头颅，那你有什么好怕的？",
    "Crafters can create unique items with materials found from battle. Keep an eye out for what loot you are receiving from individual enemies.": "工匠可以使用从战斗中获得的材料制作独特的物品。 留意你从个别敌人那里得到的战利品。",
    "Growing up, you were always inspired by the stories of heroes and their tales of incredible deeds and dauntless courage. You were never the fastest nor the strongest, but you always tried. When others would falter, you stayed steady.": "在成长过程中，您总是受到英雄故事以及他们令人难以置信的事迹和无畏勇气的故事的启发。 你从来不是最快的，也不是最强壮的，但你一直在努力。 当别人动摇时，你保持稳定。",
    "has arrived to greet you with": "已经到达迎接你",
    "he says. True to the stories,": "他说。 真实的故事，",
    "Hermes": "爱马仕",
    "If": "如果",
    "just behind him.": "就在他身后。",
    "Like": "喜欢",
    "says as he hands you a pair of sandals.": "边说边递给你一双凉鞋。",
    "says as she and": "说她和",
    "says as she turns to you.": "她转向你时说。",
    "She hands you the shield, its surface so clean it looks almost like a mirror.": "她把盾牌递给你，它的表面干净得就像一面镜子。",
    "She replies, the strong scent of incense filling the room. You've done it. Year after year you have tried, and you have finally succeeded. As you kneel, elated, exhausted, you begin to offer up a prayer.": "她回答说，房间里弥漫着浓烈的熏香气味。 你已经做到了。 年复一年你尝试过，你终于成功了。 当你跪下时，兴高采烈，筋疲力尽，你开始祈祷。",
    "steps forward towards you, shield in hand.": "手持盾牌朝你走来。",
    "steps out from behind the trees, grabbing a pair of sandals and putting them on.": "从树后走出，抓起一双凉鞋穿上。",
    "Theseus": "忒修斯",
    "Towns offer respite and the opportunity to trade. Every few seconds, you will regain HP. Click the 'General' option to see new equipment options.": "城镇提供休息和贸易机会。 每隔几秒，您将恢复 HP。 单击“常规”选项以查看新设备选项。",
    "Under settings, you can adjust the speed at which story scenes progress or skip the story entirely. You can always review the story, as well as tutorial tips and recently gained loot, by clicking the Log button on the top right.": "在设置下，您可以调整故事场景的进展速度或完全跳过故事。 您可以随时查看故事、教程提示和最近获得的战利品，方法是单击右上角的“日志”按钮。",
    "Use the section on the right to quickly view useful information such as the amount of coins you currently have. Hover over each quick view icon for more information.": "使用右侧的部分可以快速查看有用的信息，例如您当前拥有的硬币数量。 将鼠标悬停在每个快速查看图标上以获取更多信息。",
    "vanish back into the grove.": "消失在树林中。",
    "We need allies, and I believe that you can help us. Prove your resolve once more. Trace the steps and trials of champions past. Let their strength be yours.”": "我们需要盟友，我相信你能帮助我们。 再次证明你的决心。 追溯冠军过去的脚步和考验。 让他们的力量成为你的力量。”",
    "You arrive at the temple. The lone figure inside is an oracle, mixing powders together under the light of a single flame.": "你到达了寺庙。 里面孤独的身影是一个神谕，在单一火焰的光芒下将粉末混合在一起。",
    "you ask, falling to your knees.": "你问，跪倒在地。",
    "You reply.": "你回复。",
    "You've acquired your first equipment item. Click on 'Adventurer' on the top left of the screen to quickly jump to the menu and view the character page. Use the 'Change Equipment' button to update your equipment.": "你已经获得了你的第一件装备。 点击屏幕左上角的“冒险者”可以快速跳转到菜单并查看角色页面。 使用“更改设备”按钮更新您的设备。",
    "You've gained a reward by completing an achievement. View all achievements and rewards in the menu under Achievements.": "您通过完成一项成就获得了奖励。 在成就下的菜单中查看所有成就和奖励。",
    "You've never moved this fast before. Heart pounding, you start to really believe you can do this.": "你以前从未移动得这么快。 心跳加速，你开始真正相信你能做到。",
    "Your triumphs have inspired the people of Greece and have motivated some to follow you. Use the Followers menu to assign followers to search completed zones for items or pray to the gods for boons.": "你的胜利鼓舞了希腊人民，并激励一些人追随你。 使用“追随者”菜单分配追随者在已完成的区域中搜索物品或向众神祈祷以获得恩惠。",
    "Active Boon Effect": "激活的恩惠效果",
    "All Active Boon Effect": "全部激活的恩惠效果",
    "Critical Damage Up": "暴击伤害上升",
    "for a boon and you receive": "一个恩惠，你收到",
    "Heal all party members for 5 HP every 7.5 seconds.": "每 7.5 秒为所有队员恢复 5 点生命值。",
    "Heal Party Over Time": "随着时间的推移治愈队员",
    "You pray to": "你祈祷 ",
    "Euryale": "欧律阿勒",
    "Stheno": "丝西娜",
    "uses Feint.": "使用假动作。",
    "Feint": "假动作",
    "uses Snake Bite on": "使用蛇咬",
    "Snake Bite": "蛇咬",
    "When she first came to me, I must confess I did not like the idea. Time is a delicate thing, you see. But I relented for one reason. I think your journey is a necessary one. I hope that one day, you will be able to tell me truthfully what it means to be a hero. You, above all, will have the experience necessary. I wish you luck.”": "当她第一次来找我时，我必须承认我不喜欢这个主意。 你看，时间是个微妙的东西。 但出于一个原因，我心软了。 我认为你的旅程是必要的。 我希望有一天，你能如实告诉我什么是英雄。 最重要的是，您将拥有必要的经验。 祝你好运。”",
    "You go through the motions as you ascend your way through Asphodel. Hit this, dodge that, keep moving. Your fall from such high heights down to the depths of failure remind you of your thoughts as a youth. You've known how to go through the motions, but you were always one step behind.": "当您通过 Asphodel 登高时，您会经历这些动作。 打这个，躲那个，继续移动。 你从那么高的高度跌落到失败的深处，让你想起了你年轻时的想法。 你知道如何走过场，但你总是落后一步。",
    "Different notification colors indicate different things. Blue notification icons always indicate the way to go to progress the main story. Purple notification icons are optional professions that you may take on to improve your combat capabilities. Green notification icons lead to resets, which usually mean you weaken yourself in the short term to get stronger in the long term.": "不同的通知颜色表示不同的事情。 蓝色通知图标始终指示主要故事的进展方式。 紫色通知图标是可选的职业，您可以选择这些职业来提高您的战斗能力。 绿色通知图标会导致重置，这通常意味着您会在短期内削弱自己，以便在长期内变得更强大。",
    "for as long as I can remember. Once as a child, I spent hours in the forest looking for bears hoping they would take me in. I never thought I'd ever have the chance to walk in her footsteps like this. Considering we were just given a second chance… I can't miss this opportunity!”": "从我记事起。 小时候，我花了几个小时在森林里寻找熊，希望它们能收留我。我从没想过我有机会像这样追随她的脚步。 考虑到我们刚刚得到第二次机会……我不能错过这个机会！",
    ". All my life, I've been a hunter. When you're alone in the forest, tracking a wild animal for days.. things don't always go as planned. Maybe you lose the trail, maybe what you're tracking gets the better of you. Setbacks happen. But just because you lose the trail doesn't mean you can't pick it up again.”": ". 我一生都是猎人。 当您独自一人在森林中追踪野生动物数天时……事情并不总是按计划进行。 也许您迷路了，也许您正在追踪的东西使您变得更好。 挫折发生。 但仅仅因为你失去了足迹，并不意味着你不能再拾起它。”",
    "As you emerge from the Underworld, you feel the warmth of the sun on your skin for the first time in what feels like ages. You close your eyes against the brightness, hoping the sun will wash away some of your self-doubt as well. Your conversation with": "当你从地底世界出来时，你第一次感受到阳光照在你皮肤上的温暖，这感觉像是很久以前的事了。 你闭上眼睛，希望阳光也能洗去你的一些自我怀疑。 你与",
    "As you traverse the underworld, you start to understand the madness of the souls you've met. You've always taken for granted the welcoming sound of the wind at your back, the birds chirping to each other, the leaves rustling as dogs run past you. But here, there is nothing but deafening silence. All you have to hear are the screams of souls long dead... and your own thoughts.": "当你穿越地下世界时，你开始了解你遇到的灵魂的疯狂。 你总是认为背后吹来的风声、鸟儿的鸣叫声、狗从你身边跑过时树叶沙沙作响都是理所当然的。 但在这里，除了震耳欲聋的寂静之外，什么也没有。 您所听到的只是死去已久的灵魂的尖叫……以及您自己的想法。",
    "As you finally approach your destination, your contemplative trance is broken by the hustle and bustle of the coliseum. This seems to be the largest gathering of souls in the underworld and you two aren't the only ones who want a ticket out.": "当您终于接近目的地时，您沉思的恍惚被体育馆的喧嚣打破了。 这似乎是地下世界最大的灵魂聚会，而且你们两个不是唯一想要门票的人。",
    "Large Charm of Air Protection:": "空气保护大护身符：",
    "Large Charm of Artemis": "阿尔忒弥斯的大符咒",
    "Large Charm of Athena:": "雅典娜的大护身符：",
    "Large Charm of Fire Protection:": "防火大护身符：",
    "Large Charm of Holy Destruction:": "神圣毁灭大符咒：",
    "Large Charm of Preparation:": "准备的大护身符：",
    "Lethe Basin": "忘川盆地",
    "Lethe Tributary": "忘川支流",
    "Long": "长的",
    "looks to you, but you offer up no response.": "看着你，但你没有回应。",
    "making her way back to you.": "让她回到你身边。",
    "Molten Armor": "熔岩盔甲",
    "Molten Armor:": "熔岩盔甲：",
    "Molten Ring": "熔火指环",
    "Molten Ring:": "熔火戒指：",
    "Molten Shield": "熔岩之盾",
    "Molten Shield:": "熔岩护盾：",
    "Narcissuses:": "水仙花：",
    "Nature (Overdrive)": "自然（过载）",
    "Necklace": "项链",
    "New Class: Priest": "新职业：牧师",
    "New Class: Warrior": "新职业：战士",
    "Nimble Strike": "敏捷打击",
    "NO CIRCUMSTANCES": "没有任何情况",
    "On Auto Attack:": "关于自动攻击：",
    "Out of Stock": "缺货",
    "Overdrive Gain Bonus:": "超速增益奖励：",
    "Palace of Hades": "冥府",
    "Paralyzing Volley": "麻痹齐射",
    "Paralyzing Volley Upgrade 6": "麻痹凌空升级 6",
    "Pelopos Nisos": "伯罗奔尼撒岛",
    "Pendant of Fortune": "幸运坠饰",
    "Pendant of Fortune:": "幸运吊坠：",
    "Petrified Barks:": "石化树皮：",
    "Pinning Shot": "钉住射击",
    "Poison an enemy, dealing 7 damage every 3 seconds for 12 seconds.": "使敌人中毒，每 3 秒造成 7 点伤害，持续 12 秒。",
    "Poison Fang": "毒牙",
    "Possible Loot:": "可能的战利品：",
    "Pray": "祈祷",
    "Priest": "牧师",
    "Quick Completion Reward:": "快速完成奖励：",
    "Really?": "真的吗？",
    "recounts the events of the story, she kneels down to feel the earth below her feet. These grounds are obviously sacred to her. The sounds of approaching centaurs bring": "讲述故事的经过时，她跪下来感受脚下的大地。 这些理由对她来说显然是神圣的。 接近半人马的声音带来",
    "Reduce all characters' Ability Cooldowns by": "减少所有角色的技能冷却时间",
    "Reduce all characters' Air damage taken by": "减少所有角色受到的空气伤害",
    "Reduce all characters' Fire damage taken by": "减少所有角色受到的火焰伤害",
    "Reduce all characters' Water damage taken by": "减少所有角色受到的水伤害",
    "Reduce damage taken by": "减少受到的伤害",
    "Ring": "戒指",
    "Rough Emerald Fragments:": "粗糙的祖母绿碎片：",
    "Rough Opal Fragments:": "粗糙的蛋白石碎片：",
    "Rough Ruby Fragments:": "粗糙的红宝石碎片：",
    "Rough Topaz Fragments:": "粗糙的黄玉碎片：",
    "round 1": "第1轮",
    "round 2": "第二轮",
    "said, your potential is undeniable! Your companion kneels beside you, inspecting the snake-like hair of the Gorgon.": "说，你的潜力不可否认！ 你的同伴跪在你身边，检查着蛇发女妖的蛇发。",
    "says as he leads you to an empty part of the room.": "他边说边领你到房间的空旷区域。",
    "says as she walks through the coliseum gates.": "她走过体育馆大门时说。",
    "Second Wind Upgrade 5": "第二次风升级 5",
    "seconds, forcing all attacks to target you. 35.46 second cooldown.": "秒，迫使所有攻击都以你为目标。 35.46 秒冷却时间。",
    "Shatter": "粉碎",
    "She says.": "她说。",
    "Shield Slam": "盾牌猛击",
    "Shortly after finishing up with Medusa, you next journey to Nemea back near Athens. With the strength you possess, nothing short of": "完成美杜莎后不久，您将前往雅典附近的尼米亚。 以你拥有的实力，无所不能",
    "sits here above all others, staring at you with a piercing gaze.": "高高在上地坐在这里，用锐利的目光注视着你。",
    "Small Charm of Air Protection:": "空气防护小护身符：",
    "Small Charm of Artemis:": "阿尔忒弥斯的小护身符：",
    "Small Charm of Athena:": "雅典娜小护身符：",
    "Small Charm of Determination:": "决心小护身符：",
    "Small Charm of Fire Destruction:": "小火灭符：",
    "Small Charm of Hermes:": "爱马仕的小护身符：",
    "Small Charm of Holy Destruction:": "神圣毁灭小符咒：",
    "Small Charm of Vulnerability:": "漏洞的小护身符：",
    "Small Charm of Water Destruction:": "水毁小符咒：",
    "Small Charm of Water Protection:": "防水小护身符：",
    "Soul Sparks:": "灵魂火花：",
    "Sparring Match": "陪练赛",
    "special": "特殊",
    "Special Delivery": "特快专递",
    "Spirit Bow": "精灵弓",
    "Spirit Bow:": "精神弓：",
    "Spirit Essences:": "灵魂精华：",
    "standard": "标准",
    "Start Tournament": "开始比赛",
    "Steel Armor": "钢甲",
    "Steel Armor:": "钢甲：",
    "Steel Sword": "钢剑",
    "Steel Sword:": "钢剑：",
    "still favor us. Maybe this was part of their  plan?”": "还是喜欢我们。 也许这是他们计划的一部分？”",
    "still lingers on your mind. What is it to be a hero? Am I really capable of answering that question?": "仍然萦绕在你的脑海中。 什么是英雄？ 我真的有能力回答这个问题吗？",
    "Stone Blast": "石头爆破",
    "Stone Elemental": "石头元素",
    "Take Flight": "搭乘飞机",
    "The Depths": "深渊",
    "The old man chuckled.": "老者呵呵一笑。",
    "The Priest class focuses on keeping the party healthy with healing and barrier effects.": "牧师阶级专注于通过治疗和屏障效果保持聚会健康。",
    "The Warrior class focuses on taking damage as much as dealing damage with the ability to force enemies' attention and increase defense when HP is low.": "Warrior 职业专注于承受伤害和造成伤害一样，能够在 HP 低时吸引敌人的注意力并增加防御力。",
    "then deal": "然后交易",
    "This is still a work in progress!": "这仍在进行中！",
    "This is what": "这是什么",
    "TKN": "TKN",
    "took to her and she became one with the wilds. And in turn, she became": "接受了她，她与荒野融为一体。 反过来，她成为",
    "Tournament of the Dead": "死者锦标赛",
    "Travel Post (Town)": "旅游邮局（镇）",
    "Traveler": "旅行者",
    "True Shot Upgrade 5": "真实射击升级 5",
    "trusted you to handle. Time to make her proud.": "相信你来处理。 是时候让她骄傲了。",
    "used magic..”": "用了魔法……”",
    "Venomstrike:": "毒液打击：",
    "Vials of the Lethe:": "忘川之瓶：",
    "waiting for you at the front gates.": "在前门等你。",
    "Warrior": "战士",
    "was abandoned at birth. Can you imagine, a babe alone in a dangerous place like this? And yet, to survive and accomplish all that she did!”": "出生时被遗弃。 你能想象，一个婴儿独自在这样危险的地方吗？ 然而，为了生存并完成她所做的一切！”",
    "was tasked with twelve impossible tasks, forced to battle terrifying beasts and recover mystifying objects. First up was the lion terrorizing the countryside of Nemea.": "被赋予十二项不可能完成的任务，被迫与可怕的野兽战斗并找回神秘物品。 首先是狮子恐吓尼米亚的乡村。",
    "Water Damage Bonus:": "水伤害奖励：",
    "Water Resistance Bonus:": "防水奖励：",
    "were": "是",
    "Wheel of Flames": "烈焰之轮",
    "whispers to you, cracking a smile.": "对你耳语，露出微笑。",
    "will the fools of Olympus be allowed to fall. I will not have them here. Now go.”": "奥林匹斯山的愚人会被允许堕落吗？ 我不会让他们在这里。 现在，走吧。”",
    "With one final attack, you slice Medusa's head clean off. With the power of the gods, what felt impossible before is now within your reach. Despite what": "通过最后一次攻击，您将美杜莎的头砍得一干二净。 凭借众神的力量，以前认为不可能的事情现在触手可及。 尽管",
    "With that, the man turned and walked away. As you absorb the conversation that just occurred, you see": "说完，男人转身就走。 当你吸收刚刚发生的对话时，你会看到",
    "You do feel a little better. Together, you continue to press forward.": "你确实感觉好多了。 你们一起继续向前推进。",
    "You had wondered how all of this was possible, ever since you were taken from Aigosthena to Delphi in an instant.": "自从你被瞬间从 Aigosthena 带到德尔福后，你就想知道这一切是怎么可能的。",
    "You hear from a familiar voice.": "你听到一个熟悉的声音。",
    "You look at": "你看",
    "You look to your side as an old man approaches you.": "当一个老人接近你时，你看着你的身边。",
    "You nod your head, just happy to have someone else make the decision.": "你点点头，很高兴让别人做决定。",
    "You say to": "你说到",
    "You will temporarily lose access to previous Ballads after completing the following battle, turn back now if you have unfinished business.": "完成以下战斗后，您将暂时无法访问之前的歌谣，如果您有未完成的事情，请立即返回。",
    "You win! The crowd of souls cheer as you make your way to the front of the arena.": "你赢了！ 当您走到竞技场前面时，人群欢呼。",
    "Your partner moves out of the line towards you while": "你的搭档向你移动，同时",
    " Any negative status effects on the target have their duration increased by": "对目标的任何负面状态影响的持续时间都会增加",
    " Stun the target for": "  击晕目标",
    ", keeper of time. Yes,": "，时间的守护者。 是的，",
    ", noticing the stark contrast in your demeanor, pauses for a moment.": "，注意到你举止中的鲜明对比，停顿了片刻。",
    ", uncertain.": "，不确定。",
    ". A word.”": ". 一个字。”",
    "'s arrow.”": "的箭。”",
    "'s labors could stop you.": "的劳动可能会阻止你。",
    "'s thoughts mirror your own. You thought your destiny was to be a hero -- but that had all gone up in smoke. Is this all you were meant for?": "的想法反映了你自己的想法。 你以为你的命运是成为英雄——但这一切都烟消云散了。 这就是你的本意吗？",
    "“A simple answer, but not wrong. I am": "“一个简单的答案，但没有错。 我是",
    "“All I've done... and still I go to Asphodel?”": "“我都做了……我还去 Asphodel 吗？”",
    "“Any ideas on where to go next?”": "“关于下一步去哪里有什么想法吗？”",
    "“Asphodel?": "“水仙花？",
    "“Asphodel.”": "“水仙花。”",
    "“Before we fell, I felt invincible. As if there was nothing any hero had done that we couldn't do. But now, honestly, I don't know.”": "“在我们倒下之前，我觉得自己立于不败之地。 好像没有任何英雄做过我们做不到的事。 但现在，老实说，我不知道。”",
    "“Believe it or not, even": "“信不信由你，即使",
    "“Continue past the coliseum and you will find Charon ready to ferry you back to the surface. You are free to go, under one condition. Under": "“继续穿过竞技场，你会发现卡戎准备把你送回地面。 在一个条件下，你可以自由离开。 在下面",
    "“Get up, let's get you situated here. Time to go see": "“起来，我们让你坐在这里。 有时间去看",
    "“Great, then I'll decide. Let's go to Calydon. I've idolized": "“好吧，那我来决定。 我们去卡利登吧。 我崇拜过",
    "“Guess you": "“猜你",
    "“He's a man of few words. Much like yourself lately!”": "“他是个沉默寡言的人。 最近很像你自己！”",
    "“Hello, child.”": "“你好，孩子。”",
    "“Hey, we're up next. Ready?”": "“嘿，我们下一个。 准备好？”",
    "“I just assumed": "“我只是假设",
    "“I'll go sign us up, wait here.”": "“我去报个名，你在这里等着。”",
    "“Lead the way.”": "“带路。”",
    "“Let's do this. Our story doesn't have to be over yet.”": "“我们开工吧。 我们的故事还没有结束。”",
    "“Listen": "“听",
    "“Little heroes! I've been looking for ya. Come on over, don't be shy!”": "“小英雄们！ 我一直在找你。 过来，别害羞！”",
    "“Perhaps not in the flesh, but I have been with you since your journey began. I hear that we slayed the lady Medusa. Tell me, haven't you wondered how? She was already dead, slain by the Founder of Mycenae. How can that be?”": "“也许不是肉身，但自从你开始旅程以来，我就一直和你在一起。 我听说我们杀死了美杜莎女士。 告诉我，你没想过怎么做吗？ 她已经死了，被迈锡尼的创始人所杀。 怎么可能？”",
    "“Right, well I've left you two to brood long enough. Let's have a quick chat.”": "“好吧，我已经让你们两个沉思了够久了。 让我们快速聊聊。",
    "“Somewhere in all this wilderness is where": "“在这片荒野中的某个地方",
    "“Sorry, have we met?”": "“抱歉，我们见过吗？”",
    "“That's one name off my list. Who's next?”": "“那是我名单上的一个名字。 谁是下一个？”",
    "“Well done! Couldn't have done too much better myself. I think I may have been mistaken about you two. You're not wrong for the job, you just need a little guidance. Call on me when you need help, I'm never too far. See you around!”": "“做得好！ 我自己做得再好不过了。 我想我可能误会了你们两个。 你对这份工作没有错，你只需要一点指导。 当你需要帮助时打电话给我，我永远不会太远。 再见！”",
    "“Well on the plus side, it looks like": "“从好的方面来说，它看起来像",
    "“You're right. Thank you.”": "“你说得对。 谢谢。”",
    "1 follower is  attempting to activate Small Altars that your party has fulfilled the conditions for, each providing a 25% chance to activate any Small Altar among your three available altars every minute.": "1 名追随者正在尝试激活您的队伍已满足条件的小祭坛，每个小祭坛每分钟有 25% 的机会激活您三个可用祭坛中的任何一个小祭坛。",
    "1 follower is  preparing Small Altars to the gods, each providing a 2% chance to pray to a random god's Small Altar every minute.": "1个追随者正在为神灵准备小祭坛，每人每分钟有2%的几率向随机神灵的小祭坛祈祷。",
    "1 follower is  searching Aigosthena for 3 Light Leathers, 5 Throwing Stones and 3 Healing Herbs.": "1 位追随者正在寻找 Aigosthena 以获取 3 轻型皮革、5 飞石和 3 药草。",
    "1 follower is  searching Asphodel for 3 Soul Sparks.": "1 位追随者正在搜索 Asphodel 以寻找 3 个 灵魂火花。",
    "1 follower is  searching Isle of Libya for 3 Fennel and 2 Olives.": "1 位追随者正在利比亚岛寻找 3 个茴香和 2 个橄榄。",
    "1 follower is  searching Road to Dodona for 3 Olives, 3 Leathers and 4 Fennel.": "1 位追随者搜索 通往多多纳的道路 得到 3 橄榄, 3 皮革 和 4 茴香。",
    "1 Freely Enter and Leave Underworld": "1 自由进出地下世界",
    "1 Large Charm of Fire Destruction": "1 大火焰毁灭符咒",
    "1 Large Charm of Ingenuity": "1 匠心之大护身符",
    "3 Fennel, 2 Olives": "3 个茴香，2 个橄榄",
    "3 Light Leathers, 5 Throwing Stones, 3 Healing Herbs": "3 轻皮, 5 投掷石, 3 药草",
    "3 Olives, 3 Leathers, 4 Fennel": "3 个橄榄，3 个皮革，4 个茴香",
    "A Giant?! You hadn't expected to encounter one so early on your journey, but here was one in your way. It seems like he was waiting for you.": "一个巨人？！ 您没想到会在您的旅程中这么早就遇到一个，但这是您的方式。 他好像在等你。",
    "a little too green. Don't be disappointed, not everyone can be the ultimate champion of the gods can they?”": "有点太绿了。 别失望，不是每个人都能成为诸神的终极冠军吧？”",
    "Ability Cooldown Reduction:": "技能冷却缩减：",
    "Air Resistance Bonus:": "空气阻力奖励：",
    "Alchemy allows you to craft battle items that you can use to aid your party or hinder your foes.": "炼金术允许你制作战斗物品，你可以用来帮助你的队伍或阻碍你的敌人。",
    "All auto attacks and non-elemental abilities have the Earth element.": "所有自动攻击和非元素能力都具有土元素。",
    "An orange notification icon means there is a side quest available. You do not need to follow the path of a side quest to progress the story, but typically there will be a useful reward at the end.": "橙色通知图标表示有支线任务可用。 你不需要按照支线任务的路径来推进故事，但通常最后会有一个有用的奖励。",
    "approached me and together we devised a spell that would allow someone to slip in and out of the past to see those who are no longer living.": "走近我，我们一起设计了一个咒语，可以让某人溜进和溜出过去，看看那些已经不在人世的人。",
    "As": "作为",
    "as she speaks. The fire in her heart and belief in herself is contagious.": "正如她所说。 她心中的火焰和对自己的信念是会传染的。",
    "As you make your way from the opening of the Underworld near Lake Lerna towards Calydon,": "当你从 勒纳湖 附近的 地下世界 入口前往 卡利东 时，",
    "As you make your way out of the arena, you find": "当你走出竞技场时，你会发现",
    "As you work your way around the roads of Nemea, you find a towering figure blocking the path.": "当您在 Nemea 的道路上前行时，您会发现一个高大的身影挡住了去路。",
    "asks you, snapping you out of your thoughts.": "问你，把你从思绪中惊醒。",
    "Asphodel": "水仙花",
    "Asphodeluses:": "水仙：",
    "Atalanta": "亚特兰大",
    "auto attacks. Their damage is increased by": "自动攻击。 他们的伤害增加了",
    "back to her feet.": "回到她的脚边。",
    "Ballad of the Boar": "野猪之歌",
    "Ballad of the Underworld": "冥界之歌",
    "Battle Cry": "战斗口号",
    "begins to tell you of her favorite hero.": "开始告诉你她最喜欢的英雄。",
    "Blind for": "盲目的",
    "Blinding Light": "致盲光",
    "Blinding Light Upgrade 3": "致盲之光升级 3",
    "Centaur Mystic": "半人马神秘主义者",
    "Change Class": "改变类",
    "Chthonic Power:": "魔力：",
    "Coliseum": "体育馆",
    "Coliseum (Town)": "体育馆（镇）",
    "commands, assigning you to the afterlife of the ordinary. You shuffle out of the procession of those waiting to be given their final resting place as your partner steps up to take your place at the head of the line.": "命令，将您分配给普通人的来世。 当你的搭档走上前来接替你排在队伍的最前面时，你从那些等待获得最后安息地点的队伍中慢慢走出来。",
    "Commune with the Spirits": "与灵魂交流",
    "Complete 5 rounds in 300 seconds.": "在 300 秒内完成 5 轮。",
    "Complete as many rounds as you can in 300 seconds. Each round is progressively more difficult. Gain one entry per day.": "在 300 秒内完成尽可能多的回合。 每一轮都越来越困难。 每天获得一个条目。",
    "converse.": "交谈。",
    "damage after each auto attack or ability. 59.1 second cooldown.": "每次自动攻击或技能后造成的伤害。 59.1 秒冷却时间。",
    "damage to all targets and apply a": "对所有目标造成伤害并应用",
    "damage to all targets and paralyze them for": "对所有目标造成伤害并使其瘫痪",
    "Darkened Meadows": "黑暗的草地",
    "Darkness is all you see as you float down.": "当你漂浮下来时，你所看到的都是黑暗。",
    "Darkness.": "黑暗。",
    "Deal an additional 28 damage.": "额外造成 28 点伤害。",
    "Decrease damage taken by 21%.": "减少 21% 受到的伤害。",
    "decree that your partner will be joining you in Asphodel.": "宣布您的伴侣将加入您的 Asphodel。",
    "Defeat 20 more times for more info.": "再击败 20 次以获取更多信息。",
    "Defeat 3 more times for more info.": "再击败 3 次以获取更多信息。",
    "Down. Down to the Underworld.": "向下。 下到冥界。",
    "DPS Required To Complete:": "需要完成的 DPS：",
    "Draw all targets' focus for the next": "为下一个绘制所有目标的焦点",
    "Eagle Feathers:": "鹰羽：",
    "Earth Damage Dealt:": "地球伤害处理：",
    "Earth Damage Taken:": "对地球造成的伤害：",
    "Earth damage to a target and reduce their Agility by": "对一个目标造成大地伤害并使其敏捷降低",
    "Earth damage to all targets. 28 second cooldown.": "对所有目标造成大地伤害。 28 秒冷却时间。",
    "Elysian Oak Bow": "极乐橡木弓",
    "Elysian Oak Bow:": "极乐橡木弓：",
    "Elysium": "极乐世界",
    "Elysium - Coliseum": "极乐世界 - 体育馆",
    "Endless Staircase": "无尽的楼梯",
    "Entries Remaining:": "剩余条目：",
    "Essences of Fire:": "火焰精华：",
    "Eternal Melee": "永恒混战",
    "Exploding Potion": "爆炸药水",
    "Exploding Potions:": "爆炸药水：",
    "Expose Weakness": "暴露弱点",
    "Fending Mace": "抵御权杖",
    "Fending Mace:": "抵御权杖：",
    "Fennel:": "茴香：",
    "Fiery Passage": "火热的通道",
    "Fire Damage Bonus:": "火焰伤害加成：",
    "Fire Resistance Bonus:": "耐火加成：",
    "First Time Completion Reward:": "首次完成奖励：",
    "Flames of Tartarus": "塔尔塔罗斯的火焰",
    "Floating Spirit": "浮灵",
    "For 20 seconds, all non elemental attacks take on the element of the last elemental attack you used while this effect is active.": "在 20 秒内，所有非元素攻击都将采用你在此效果激活时使用的最后一次元素攻击的元素。",
    "for all debuffs created by the character equipped with Artemis.": "对于装备有 Artemis 的角色所造成的所有减益效果。",
    "for the character equipped with Athena.": "对于装备雅典娜的角色。",
    "for the character equipped with Hermes.": "对于装备爱马仕的角色。",
    "Forgotten Halls": "被遗忘的大厅",
    "Forgotten Locket": "被遗忘的挂坠盒",
    "Forgotten Locket:": "被遗忘的挂坠盒：",
    "Free from gods for the time being, you begin the short trek to the ferryman of the Underworld.": "暂时摆脱众神的束缚，你开始了前往冥界摆渡人的短途跋涉。",
    "Gain increasing XP and Coin rewards the further you progress!": "获得越来越多的 XP 和金币奖励，你进步得越远！",
    "Gemmed Necklace": "宝石项链",
    "Goldroot": "金根",
    "Goldroots:": "金根：",
    "Grant all characters a": "授予所有角色一个",
    "guides all souls down to the underworld, so it would seem the gravity of dying means little to him. You say nothing as you hear": "引导所有的灵魂下到阴间，所以死亡的重力对他来说似乎无关紧要。 你什么也没说",
    "Hades": "哈迪斯",
    "has looked after me as well, when no one else would. Without her, I would never have made it this far. No matter how many times I fall, I won't fail her.”": "在没有其他人会照顾我的时候也照顾过我。 没有她，我永远不会走到这一步。 无论跌倒多少次，我都不会辜负她。”",
    "Heal": "治疗",
    "Heal a party member for": "治疗一名队员",
    "Heavenly Shield": "天堂之盾",
    "Holy Damage Bonus:": "神圣伤害加成：",
    "HP Shield, up to": "生命值 护盾，最高",
    "Immediately perform": "立即执行",
    "included. During a lull in your fighting,": "包括。 在你打架的间歇期，",
    "Increase all characters' Critical Damage Multiplier by": "增加所有角色的暴击伤害倍率",
    "Increase all characters' Fire damage by": "增加所有角色的火焰伤害",
    "Increase all characters' Water damage by": "增加所有角色的水伤害",
    "Increase Debuff Duration by": "减益持续时间增加",
    "Increase Healing Received from all sources by": "增加从所有来源获得的治疗量",
    "Increase Overdrive gauge gain from all sources by": "将所有来源的 超频 仪表增益提高",
    "Increase Overdrive gauge gain from auto attacks by": "将自动攻击的 超频 槽增益提高",
    "Increase the party's Earth Damage Dealt by": "增加队伍的土系伤害",
    "Increase your Attack and Agility by": "增加你的攻击和敏捷",
    "insists on a detour through Mount Parthenion. The mountain is home to many a wild spirit and the birth place of several heroes' origin stories,": "坚持绕道帕提尼翁山。 这座山是许多野性精灵的家园，也是数位英雄出身故事的诞生地，",
    "Instantly receive 5,000 Bonus XP": "立即获得 5,000 奖励 经验",
    "is concerned about the impending war for Olympus. There's going to be a tournament in the Coliseum of Elysium.": "担心即将到来的奥林匹斯战争。 极乐世界竞技场将举行一场锦标赛。",
    "is granting the winner, or winners, passage from the Underworld so long as they fight with Olympus when the time comes. I don't know if you really have what it takes but… why not give it a shot?”": "只要他们在时机成熟时与奥林匹斯山战斗，就会授予胜利者或胜利者从黑社会的通道。 我不知道你是否真的有能力，但是……为什么不试一试呢？”",
    "Isle Center": "岛中心",
    "it bellows as it makes its way towards you.": "它朝你走来时会吼叫。",
    "Khronos": "科罗诺斯",
    "Iron Armor:": "铁盔甲：",
    "Iron Shield:": "铁盾牌：",
    "Short Bow:": "短弓：",
    "+1 Large Charm of Haste": "+1 大型加速符咒",
    "+1 Large Charm of Lightning Protection": "+1 大型防雷符咒",
    "+1 Large Charm of Vulnerability": "+1 大护身符",
    "+1 Small Charm of Determination": "+1 小型决心护符",
    "+1 Small Charm of Fire Destruction": "+1 小型火焰毁灭符咒",
    "+1 Small Charm of Fire Protection": "+1 小型防火护身符",
    "+1 Small Charm of Haste": "+1 小型加速符咒",
    "+1 Small Charm of Holy Protection": "+1 小型神圣保护符咒",
    "+1 Small Charm of Lightning Protection": "+1 小型防雷护身符",
    "+1 Small Charm of Preparation": "+1 准备小符咒",
    "Calydon": "卡利东",
    "Heal a party member for 200 HP.": "治疗一名队员 200 HP。",
    "Heal both party members for 150 HP.": "治疗双方队员 150 HP。",
    "Increase all characters' Air damage by": "增加所有角色的空气伤害",
    "Increase all characters' Armor Penetration by": "增加所有角色的护甲穿透",
    "Increase all characters' Earth damage by": "增加所有角色的地球伤害",
    "Increase all characters' Lightning damage by": "增加所有角色的闪电伤害",
    "Reduce all characters' Auto Attack Cooldowns by": "减少所有角色的自动攻击冷却时间",
    "Reduce all characters' Earth damage taken by": "减少所有角色受到的地球伤害",
    "Reduce all characters' Holy damage taken by": "减少所有角色受到的神圣伤害",
    "Reduce all characters' Lightning damage taken by": "减少所有角色受到的闪电伤害",
    "The Lethe": "忘川",
    "Fervor": "热情",
    "For 20 seconds, your auto attack cooldown is reduced by 33%.": "在20秒内，你的自动攻击冷却时间减少33%。",
    "Hermes, Messenger of the Gods, focuses on agility and quick attacks. His abilities and upgrades can increase agility and reduce auto attack and ability cooldowns.": "赫尔墨斯，众神使者，专注于敏捷和快速攻击。他的能力和升级可以提高敏捷性，减少自动攻击和能力冷却。",
    "Nature": "自然",
    "DEF": "防御",
    "DMG": "伤害",
    "Arcadian Roads": "田园大道",
    "Travel Post": "旅行社",
    "Stymphalian Vulture": "斯廷法利亚秃鹰",
    "Steep Ascent": "陡坡",
    "Mt. Parthenion Caverns": "帕提尼翁山洞穴",
    "Foot of the Mountain": "山脚",
    "Gates of the Underworld": "地下世界之门",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Isle of Libya": "利比亚岛",
    "Arta (Town)": "阿尔塔（城镇）",
    "Arta": "阿尔塔",
    "Sybaris": "西巴瑞斯",
    "Mountain Opening": "开放的山口",
    "Delphi": "德尔福",
    "Delphi Outskirts": "德尔斐郊区",
    "Road to Dodona": "通往多多纳的道路",
    "Delphi (Town)": "德尔福（镇）",
    "Delphi": "",
    "Athena": "雅典娜",
    "Bay": "海岸",
    "Aigosthena - Bay": "Aigosthena - 海岸",
    "Aigosthena": "艾格斯特纳",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "X": "X",
    "B": "B",
    "A": "A",
    "for": "",
    "For": "",
    "|": "|",
    "★": "★",
    "⇅": "⇅",
    "↪": "↪",
    "→": "→",
    "»": "»",
    "!": "!",
    "-": "-",
    "T": "T",
    "???": "???",
    "P": "P",
    "Z": "Z",
    "★★": "★★",
    "★★★": "★★★",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Water Serpent ": "水蛇 ",
    "Upper Coast (": "上海岸（",
    "Bay (": "海湾（",
    "Delphi Outskirts (": "德尔福郊外 (",
    "Average per hour: ": "平均每小时：",
    "damage.": "伤害。",
    "Assigned Followers: ": "分配的追随者：",
    "Coastal Roads of Locris (": "洛克里斯 的沿海道路 (",
    "Highwayman ": "拦路强盗 ",
    "Thief ": "窃贼 ",
    "Weapon - ": "武器 - ",
    "Countryside (": "乡村 (",
    "Bandit ": "土匪 ",
    "Coyote ": "土狼 ",
    "Mountain Opening (": "开放的山口（",
    "Incoming DPS: ": "受到的DPS：",
    "Party DPS: ": "队伍DPS：",
    "Red-Feathered Harpy ": "红羽鹰身女妖 ",
    "Blue-Feathered Harpy ": "蓝羽鹰身女妖 ",
    "Heart of the Woods ": "树林之心 ",
    "SHIFT + ": "SHIFT + ",
    "Selling ": "出售 ",
    "Starving Mongrel": "饥饿的混血儿",
    "Lower Coast": "下海岸",
    "Western Woodlands": "西部林地",
    "- ": "- ",
    "Lamia": "女妖",
    "Road to Dodona - ": "通往多多纳的道路 - ",
    "Fledgling Lamia": "初级女妖",
    "Lake Trichonida": "特里科尼达湖",
    "Mountain Pass ": "山口",
    "Ambracian Gulf": "安布拉西亚湾",
    "Damage against this target is increased by ": "对该目标的伤害增加 ",
    "Decrease Agility by ": "敏捷降低 ",
    "Increase Luck by ": "增加幸运 ",
    "Increase Attack by ": "增加攻击 ",
    "Large Octopus": "大型章鱼",
    "Chance on Auto Attack ": "自动攻击几率 ",
    "Gorgon": "蛇发女妖",
    "Green-Feathered Harpy": "绿羽鹰身女妖",
    "Isle of Libya - ": "利比亚岛 - ",
    "You found a chest containing ": "你找到了一个宝箱装有 ",
    "Beach": "海滩",
    "Unsettling Shade": "令人不安的影子",
    "Rocky Outcrops": "露头岩石",
    "has upgraded to level ": "已升级到等级 ",
    "Decrease Attack by ": "降低攻击 ",
    "Increase Critical Damage Multiplier of all party members by ": "增加所有队员的暴击伤害乘数 ",
    "Deeper Path": "更深入的路",
    "Open Plains": "开阔平原",
    "Mt. Parthenion Caverns": "帕提尼翁山洞穴",
    "Winding Paths": "蜿蜒的路径",
    "Water-logged Marsh": "水涝沼泽",
    "Steep Ascent": "陡坡",
    "Arcadian Roads": "田园大道",
    "Revenant": "亡魂",
    "Gates of the Underworld": "地下世界之门",
    "Gates of Horn and Ivory": "号角和象牙之门",
    "Foot of the Mountain": "山脚",
    "Elysian Fields": "乐土",
    "Heavenly Shield Upgrade ": "天堂之盾升级 ",
    "Expose Weakness Upgrade ": "暴露弱点升级 ",
    "Divine Strike Upgrade ": "神圣打击升级 ",
    "Total Overdrive Points Required: ": "所需的总超频点数：",
    "Increase Defense by ": "提高防御 ",
    "Increase Earth damage dealt by ": "增加大地伤害 ",
    "Pelopos Nisos - ": "伯罗奔尼撒岛 - ",
    "Valley Opening": "开放的山谷",
    "Centaur Archer": "半人马弓箭手",
    "Centaur Scout": "半人马侦察兵",
    "Fire-Breathing Serpent": "喷火蛇",
    "Centaur Warrior": "半人马战士",
    "Unruly Hound": "顽皮的猎犬",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " wins)": " 获胜)",
    " win)": " 获胜)",
    "% of Attack": "% 攻击",
    " XP to": " 经验到",
    "Apply a damage over time effect that deals an additional": "施加一个持续伤害效果，造成额外",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^Apr (.+)([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\(([\d\.]+):([\d\.]+):([\d\.]+)\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^ \(([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^造成(.+)$/,
    /^等级(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\/ ([\d\.,]+)$/,
    /^ \/ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You received (.+) Olive.$/, '你收到 $1 橄榄.'],
    [/^You received (.+) Throwing Stone.$/, '你收到 $1 飞石.'],
    [/^You received (.+) Wax.$/, '你收到 $1 肥皂.'],
    [/^You received (.+) Poison Fang.$/, '你收到 $1 毒牙.'],
    [/^You received (.+) Petrified Bark.$/, '你收到 $1 石化树皮.'],
    [/^You received (.+) Light Leather.$/, '你收到 $1 轻型皮革.'],
    [/^You received (.+) Forgotten Locket.$/, '你收到 $1 被遗忘的挂坠盒.'],
    [/^You received (.+) Goldroot.$/, '你收到 $1 金根.'],
    [/^You received (.+) Soul Spark.$/, '你收到 $1 灵魂火花.'],
    [/^You received (.+) Spirit Bow.$/, '你收到 $1 精灵弓.'],
    [/^You received (.+) Rough Opal Fragment.$/, '你收到 $1 蛋白石原石碎片.'],
    [/^You received (.+) Fennel.$/, '你收到 $1 茴香.'],
    [/^You received (.+) Leather.$/, '你收到 $1 皮革.'],
    [/^You received (.+) Fending Mace.$/, '你收到 $1 抵御权杖.'],
    [/^You received (.+) Lamia Heart.$/, '你收到 $1 女妖之心.'],
    [/^You received (.+) Iron Sword.$/, '你收到 $1 铁剑.'],
    [/^You received (.+) Healing Herb.$/, '你收到 $1 药草.'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^HP. Targets the party member with the lowest HP \%. (.+) second cooldown.$/, '生命值。 以 生命值 % 最低的队员为目标。 $1 秒冷却时间。'],
    [/^Reach (.+) victories$/, '达到 $1 次胜利'],
    [/^\(Lv (.+) \- Ach (.+) Complete\)$/, '(等级 $1 - 成就完成 $2)'],
    [/^Deal (.+) damage to a target.$/, '对1个目标造成 $1 伤害。'],
    [/^gains (.+) HP from Divine Strike.$/, '从神圣打击中获得 $1 生命值。'],
    [/^damage to a single target (.+) times every$/, '对单个目标造成 $1 次伤害'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^ ([\d\.]+) second cooldown.$/, ' $1 冷却时间。'],
    [/^. ([\d\.]+) second cooldown.$/, '. $1 冷却时间。'],
    [/^of the original duration. ([\d\.]+) second cooldown.$/, '原始持续时间。 $1 秒冷却时间。'],
    [/^of their total health. ([\d\.]+) second cooldown.$/, '他们的整体健康状况。 $1 秒冷却时间。'],
    [/^Poison your target, dealing ([\d\.]+) damage every ([\d\.]+) seconds for ([\d\.]+) seconds.$/, '使你的目标中毒，每 $2 秒造成 $1 点伤害，持续 $3 秒。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) \/ ([\d\.,]+) XP to Level ([\d\.,]+)$/, '$1 \/ $2 经验到等级 $3'],
    [/^([\d\.]+) HP \/ ([\d\.,]+) seconds$/, '$1 生命值 \/ $2 秒'],
    [/^\+([\d\.]+) HP \/ ([\d\.,]+) Sec$/, '\+$1 生命值 \/ $2 秒'],
    [/^\+([\d\.,]+) Max HP$/, '\+$1 生命值上限'],
    [/^\+([\d\.,]+) Attack$/, '\+$1 攻击'],
    [/^\+([\d\.,]+) Coin$/, '\+$1 金币'],
    [/^\+([\d\.,]+) Olive$/, '\+$1 橄榄'],
    [/^\+([\d\.,]+) Resistance$/, '\+$1 抵抗'],
    [/^\+([\d\.,]+) Boon of Olympus$/, '\+$1 奥林匹斯的恩赐'],
    [/^\+([\d\.,]+) Light Leather$/, '\+$1 轻型皮革'],
    [/^\+([\d\.,]+) Narcissus$/, '\+$1 纳西索斯'],
    [/^\+([\d\.,]+) Soul Spark$/, '\+$1 灵魂火花'],
    [/^\+([\d\.,]+) Vial of the Lethe$/, '\+$1 忘川之瓶'],
    [/^\+([\d\.,]+) Thick Leather$/, '\+$1 厚皮革'],
    [/^\+([\d\.,]+) Asphodelus$/, '\+$1 水仙'],
    [/^\+([\d\.,]+) Vial of Lake Lerna$/, '\+$1 勒纳湖小瓶'],
    [/^\+([\d\.,]+) Rough Ruby Fragment$/, '\+$1 粗糙的红宝石碎片'],
    [/^\+([\d\.,]+) Rough Aquamarine Fragment$/, '\+$1 粗糙的海蓝宝石碎片'],
    [/^\+([\d\.,]+) Goldroot$/, '\+$1 金根'],
    [/^\+([\d\.,]+) Essence of Fire$/, '\+$1 火焰精华'],
    [/^\+([\d\.,]+) Leather$/, '\+$1 皮革'],
    [/^\+([\d\.,]+) Throwing Stone$/, '\+$1 飞石'],
    [/^\+([\d\.,]+) Healing Herb$/, '\+$1 药草'],
    [/^\+([\d\.,]+) Healing Salve$/, '\+$1 治疗药膏'],
    [/^\+([\d\.,]+) Petrified Bark$/, '\+$1 石化树皮'],
    [/^\+([\d\.,]+) Agility$/, '\+$1 敏捷'],
    [/^\+([\d\.,]+) Luck$/, '\+$1 幸运'],
    [/^\+([\d\.,]+) Defense$/, '\+$1 防御'],
    [/^([\d\.,]+):([\d\.,]+) remaining$/, '剩余 $1:$2'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Petrified Bark$/, '$1 石化树皮'],
    [/^([\d\.,]+) Wax$/, '$1 蜡'],
    [/^([\d\.,]+) XP$/, '$1 经验'],
    [/^([\d\.,]+) Olive$/, '$1 橄榄'],
    [/^([\d\.,]+) Throwing Stone$/, '$1 飞石'],
    [/^([\d\.,]+) Bronze Armor$/, '$1 青铜盔甲'],
    [/^([\d\.,]+) Bronze Hammer$/, '$1 青铜锤子'],
    [/^([\d\.,]+) Bronze Sword$/, '$1 青铜剑'],
    [/^([\d\.,]+) Coin$/, '$1 金币'],
    [/^([\d\.,]+) Lamia Heart$/, '$1 女妖之心'],
    [/^([\d\.,]+) Defense$/, '$1 防御'],
    [/^([\d\.,]+) Leather$/, '$1 皮革'],
    [/^([\d\.,]+) Attack$/, '$1 攻击'],
    [/^([\d\.,]+) Agility$/, '$1 敏捷'],
    [/^([\d\.,]+) Resistance$/, '$1 抵抗'],
    [/^([\d\.,]+) Defense Permanently$/, '$1 永久防御'],
    [/^\+([\d\.,]+)\% Boon of Olympus$/, '\+$1\% 奥林匹斯的恩赐'],
    [/^\+([\d\.,]+)\% Critical Damage Bonus$/, '\+$1\% 暴击伤害加成'],
    [/^\+([\d\.,]+)\% Overdrive Gain Bonus$/, '\+$1\% 超频增益加成'],
    [/^\+([\d\.,]+)\% Fire Resistance Bonus$/, '\+$1\% 火抗加成'],
    [/^([\d\.,]+)\% of Defense$/, '$1\% 防御'],
    [/^\+([\d\.,]+) Small Charm of Ingenuity$/, '\+$1 独创的小护身符'],
    [/^\+([\d\.,]+) Poison Extract Potion Recipe$/, '\+$1 毒液提取物配方'],
    [/^\+([\d\.,]+) Poison Fang$/, '\+$1 毒牙'],
    [/^\+([\d\.,]+) Luck Permanently$/, '\+$1 永久幸运'],
    [/^\+([\d\.,]+) Defense Permanently$/, '\+$1 永久防御'],
    [/^([\d\.,]+) Bonus XP$/, '$1 奖励经验'],
    [/^([\d\.,]+) Soul Sparks$/, '$1 灵魂火花'],
    [/^([\d\.,]+) Coins$/, '$1 金币'],
    [/^([\d\.,]+) Light Leathers$/, '$1 轻型皮革'],
    [/^([\d\.,]+) Light Leather$/, '$1 轻型皮革'],
    [/^([\d\.,]+) Max HP$/, '$1 生命上限'],
    [/^([\d\.,]+) more achievements needed$/, '还需要 $1 成就'],
    [/^\(([\d\.,]+) owned\)$/, '（拥有 $1）'],
    [/^seconds. ([\d\.,]+) second cooldown.$/, '秒。 $1 秒冷却时间。'],
    [/^of the damage dealt. ([\d\.,]+) second cooldown.$/, '造成的伤害。 $1 秒冷却时间。'],
    [/^Remaining Duration: ([\d\.,]+) minutes$/, '剩余时长：$1 分钟'],
    [/^Remaining Duration: ([\d\.,]+) seconds$/, '剩余时长：$1 秒'],
    [/^Taking ([\d\.,]+) damage every ([\d\.,]+) seconds.$/, '每 $2 秒受到 $1 点伤害。'],
    [/^takes ([\d\.,]+) damage from Claw\'s effect.$/, '受到爪击效果的 $1 点伤害。'],
    [/^Deal ([\d\.,]+) damage to those who auto attack you.$/, '对自动攻击你的人造成 $1 点伤害。'],
    [/^for ([\d\.,]+) damage.$/, '造成了 $1 伤害。'],
    [/^gains ([\d\.,]+) XP and ([\d\.,]+) Affinity XP.$/, '获得 $1 经验 和 $2 亲和力 经验。'],
    [/^for ([\d\.,]+) damage as well.$/, '以及造成了 $1 伤害。'],
    [/^for ([\d\.,]+)$/, ' $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^level ([\d\.,]+)$/, '等级 $1'],
    [/^Lv ([\d\.,]+)$/, '等级 $1'],
    [/^takes ([\d\.,]+) damage from Sure Shot\'s effect.$/, '受到 必杀技 效果的 $1 点伤害。'],
    [/^takes ([\d\.,]+) damage from Snake Bite\'s effect.$/, '受到 蛇咬 效果的 $1 点伤害。'],
    [/^Clear in ([\d\.,]+) seconds$/, '$1 秒内清除'],
    [/^Affinity Level ([\d\.,]+)$/, '亲和力等级 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Condition: (.+) Overdrives$/, '条件：$1 超频'],
    [/^Condition: (.+) Victories$/, '条件：$1 胜利'],
    [/^Condition: (.+) Ability Uses$/, '条件：$1 能力使用'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);