/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Adventurer": "冒险家",
    "log": "日志",
    "Lv Up!": "升级了！",
    "menu": "菜单",
    "pause": "暂停",
    "Upper Coast": "上海岸",
    "Up to 30 minutes of away time is automated. After that, up to 8 hours is banked and allows you to run the game at double speed.": "长达 30 分钟的离开时间是自动化的。 之后，最多可存储 8 小时，并允许您以双倍速度运行游戏。",
    "Water Serpent": "水蛇",
    "AGI": "敏捷",
    "Auto Progress": "自动进度",
    "Ballad of a Champion": "冠军之歌",
    "Ballads": "歌谣",
    "'s attack hits": "的攻击命中",
    "attacks": "攻击",
    "Ballad of Heroes": "英雄之歌",
    "Critical hit!": "暴击！",
    "patreon": "赞助",
    "The enemy party has been defeated.": "敌方已被击败。",
    "uses Quick Hit on": "使用快速攻击",
    "uses Thousand Cuts.": "使用千刃斩。",
    "Your party gains": "你的队伍获得了",
    "Agility:": "敏捷：",
    "Average": "平均",
    "Coins:": "金币：",
    "Auto Attack": "自动攻击",
    "Attack Speed:": "攻击速度：",
    "Attack:": "攻击：",
    "Crustacean": "甲壳动物",
    "damage after each auto attack or ability. 60 second cooldown.": "每次自动攻击或技能后造成的伤害。 60 秒冷却时间。",
    "damage and increase Agility by": "伤害并增加敏捷",
    "Deal": "造成",
    "Defense:": "防御：",
    "Luck:": "幸运：",
    "Max HP:": "生命上限：",
    "No abilities.": "没有能力。",
    "No loot.": "没有战利品。",
    "Quick Hit": "快速攻击",
    "Resistance:": "反抗：",
    "Right click to toggle between Manual and Auto mode. Left click or press": "右键点击可在手动和自动模式之间切换。 左键单击或按下",
    "seconds, deal an additional": "秒，造成一个额外的",
    "seconds.": "秒。",
    "seconds. 18 second cooldown.": "秒。18秒冷却时间。",
    "Thousand Cuts": "千刃斩",
    "Throwing Stone": "飞石",
    "to use ability in Manual mode.": "在手动模式下使用能力。",
    "uses Overdrive: Smash.": "使用超速：粉碎。",
    "XP:": "经验：",
    "You move to": "你移动到了",
    "Jump to..": "跳转到..",
    "Ballad of the Gorgon": "蛇发女妖之歌",
    "General": "常规",
    "Latest Town": "最新城镇",
    "View Followers": "查看追随者",
    "damage.": "伤害。",
    "damage. Heal for": "伤害。造成",
    "Divine Strike": "神圣一击",
    "Holy": "神圣",
    "'s overdrive ends.": "的超速结束。",
    "activate": "激活",
    "Achievement Unlocked": "成就已解锁",
    "battle": "战斗",
    "As you proceed on your journey, you will have access to different altars to honor the gods. Select the Altar on the right and pray to Athena to gain a party-wide buff and affinity EXP for Athena.": "当您继续您的旅程时，您将可以访问不同的祭坛来纪念众神。 选择右边的祭坛，向雅典娜祈祷，可以获得全队BUFF和雅典娜亲和力经验。",
    "Thief": "窃贼",
    "Highwayman": "拦路强盗",
    "attains level": "达到等级",
    "Bandit": "土匪",
    "Battle Rewards": "战斗奖励",
    "Battle State Updates": "战斗状态更新",
    "Buy": "购买",
    "Character Level Up": "角色升级",
    "Delphi Outskirts": "德尔福郊区",
    "Each follower provides a 2% chance per minute to pray to a random god's Small Altar and receive a boon for the party. This does not require an altar to be activated. You cannot receive the same exact boon more than once at a time.": "每个追随者每分钟有 2% 的机会向随机神灵的小祭坛祈祷并为队伍获得恩赐。 这不需要激活祭坛。 您不能一次多次获得完全相同的恩赐。",
    "Each follower provides a 25% chance per minute to activate any Small Altar among your three available altars that have met their necessary activation conditions.": "每个追随者每分钟有 25% 的机会激活您三个满足必要激活条件的可用祭坛中的任何一个小祭坛。",
    "Enemy Ability Use": "敌人技能使用",
    "Enemy Auto Attacks": "敌人自动攻击",
    "Enemy Status Effect Updates": "敌人状态效果更新",
    "Equipment Effect Updates": "装备效果更新",
    "Follower Prayer": "追随者祈祷",
    "Follower Search": "追随者搜索",
    "for a new follower.": "对于一个新的追随者。",
    "Found Treasure Chest": "发现宝箱",
    "gains": "收益",
    "Game Log Editor": "游戏日志编辑器",
    "God Level Up": "上帝升级",
    "Heal a party member for 50 HP.": "治疗一名队员 50 生命值。",
    "Healing Herb": "药草",
    "misc": "杂项",
    "new followers": "新的追随者",
    "No followers are currently praying.": "目前没有追随者在祈祷。",
    "No followers are currently searching.": "当前没有追随者正在搜索。",
    "Overview": "概览",
    "Party Ability Use": "队伍能力使用",
    "Party Auto Attacks": "队伍自动攻击",
    "Party Overdrives": "队伍过载",
    "Party Status Effect Updates": "队伍状态效果更新",
    "pray": "祈祷",
    "Pray To Altar": "祈祷祭坛",
    "prayer": "祈祷者",
    "Prayer": "祈祷者",
    "Purchase": "购买",
    "search": "搜索",
    "Search": "搜索",
    "Small Altars": "小祭坛",
    "The story of your accomplishments has spread all throughout Greece. Some people have taken to follow you and are able to assist you in various ways.": "您的成就传遍了整个希腊。 有些人已经开始追随你，并能够以各种方式帮助你。",
    "Unassign All": "全部取消分配",
    "Use Battle Item": "使用战斗道具",
    "uses Divine Strike on": "对",
    "v0.42 beta": "v0.42 测试版",
    "while searching Aigosthena.": "在寻找埃苟斯提那的时候。",
    "You can assign a follower to any zone that you have cleared. Gaining achievements in a zone will increase the level of that zone, increasing the yield your followers may find.": "您可以将追随者分配到您已清除的任何区域。 在某个区域获得成就会提高该区域的等级，从而增加您的追随者可能获得的收益。",
    "You can assign a follower to pray to the gods for your success.": "您可以指派一名追随者为您的成功向众神祈祷。",
    "You gain": "你获得",
    "You receive": "你收到",
    "Your followers found": "找到您的追随者",
    "Your party has been defeated. You hurry back to the safety of town.": "你的队伍被打败了。 你赶紧回到安全的城镇。",
    "All": "全部",
    "All Items": "所有物品",
    "Armor": "盔甲",
    "Battle Items": "战斗物品",
    "Equipment": "装备",
    "Equippable Healing Item": "可装备治疗物品",
    "Iron Armor": "铁甲",
    "Iron Hammer": "铁锤",
    "Iron Shield": "铁盾",
    "Iron Sword": "铁剑",
    "Linen Armor": "亚麻盔甲",
    "New Items": "新物品",
    "Shield": "盾牌",
    "Short Bow": "短弓",
    "Show:": "显示：",
    "Unequipped": "未装备",
    "Bow": "弓",
    "Hammer": "锤子",
    "Sword": "剑",
    "Countryside": "乡村",
    "on his journey to defeat the monstrous Medusa. As you cross the countryside between Locris and Aetolia, you get the feeling you are being followed. You've battled numerous bandits on your path and before this one can get the jump on you, you go on the offensive.": "在他击败可怕的美杜莎的旅程中。 当您穿过 洛克里斯 和 埃托利亚 之间的乡村时，您会感到自己被跟踪了。 你在路上与无数强盗作战，在这个强盗抢到你之前，你继续进攻。",
    " Heal for": "治愈",
    ", the triumph and fall of": ", 的胜利与陨落",
    ", the winding journey of": ", 曲折的旅程",
    ". Could you truly be in the same conversations as these heroes?": ". 你真的能和这些英雄进行同样的对话吗？",
    ". Could you walk the path of champions? You know all of the stories by heart -- the trials of": ". 能否走上冠军之路？ 你对所有的故事都了如指掌——",
    ". View passive ability description by hovering your god's name.": ". 将鼠标悬停在你神的名字上，查看被动能力描述。",
    "1 follower is  searching Aigosthena for 3 Light Leathers.": "1 位追随者搜索 Aigosthena 时找到了 3 轻型皮革。",
    "Click or press": "单击或按下",
    "Coastal Roads of Locris": "洛克里斯 的沿海道路",
    "gains 3 HP from Second Wind.": "从复苏之风中获得 3 点生命值。",
    "Heracles": "赫拉克勒斯",
    "Increase Agility by 25%.": "敏捷提高 25%。",
    "Jason": "杰森",
    "learns a new  passive  ability:": "学习一个新的被动技能：",
    "Odysseus": "奥德修斯",
    "Perseus": "英仙座",
    "Road to Dodona - Coastal Roads of Locris": "通往多多纳的道路 - 洛克里斯 的沿海道路",
    "Road to Dodona - Countryside": "通往多多纳的道路 - 乡村",
    "Second Wind": "复苏之风",
    "See a brief overview of important resources and quick links to important locations.": "查看重要资源的简要概述和重要位置的快速链接。",
    "to toggle targeting mode. After activating, click an enemy to target all auto attacks and abilities from this character on that enemy.": "切换定位模式。 激活后，单击一个敌人可以将该角色的所有自动攻击和技能都瞄准该敌人。",
    "uses Healing Herb, gaining 50 HP.": "使用治疗草药，获得 50 生命值。",
    "You find your way out of Delphi while processing your meeting with": "您在处理与 德尔福 的会议时找到了离开 德尔福 的方法",
    "Your feet unconsciously make their way northwest towards Dodona, following the path of": "你的脚不自觉地向西北走向多多纳，沿着",
    "Archer": "弓箭手",
    "Red-Feathered Harpy": "红羽鹰身女妖",
    ", but you feel this Archer matches you in the same way. As your fight comes to a stalemate, you raise your hands in surrender.": "，但你觉得这个弓箭手和你一样匹配。 当你的战斗陷入僵局时，你举起双手投降。",
    ". The goddess": ". 女神",
    "“I didn't mean to startle you.”": "“我不是故意吓到你的。”",
    "“I thought you were trying to mug me, but you fight harder than an ordinary bandit. Why are you following me?”": "“我还以为你是来抢劫我的呢，没想到你比普通的强盗还厉害。 你为什么跟着我？”",
    "“I was leaving Delphi at the same time as you, and couldn't help notice you cutting down the outlaws running these roads. Following you made it easier to travel.. and I was curious what you were after.”": "“我和你同时离开德尔福，不禁注意到你砍掉了这些道路上的不法分子。 跟着你让旅行变得更容易……我很好奇你在追求什么。”",
    "“If you want a challenge, then walk with me to Dodona.": "“如果你想要挑战，那就和我一起去多多纳。",
    "“My name is": "“我的名字是",
    "“Sorry about that.”": "“对于那个很抱歉。”",
    "1 to all other primary stats": "1 到所有其他主要统计数据",
    "Air": "空气",
    "and": "和",
    "Archer": "射手",
    "Artemis": "阿尔忒弥斯",
    "ATK": "攻击",
    "Blue-Feathered Harpy": "蓝羽鹰身女妖",
    "Coyote": "土狼",
    "guides my arrows. She tasked me with hunting the strongest enemies I can find to prove myself worthy of defending Olympus. I almost added you to that list.”": "指引我的箭。 她指派我去猎杀我能找到的最强大的敌人，以证明我有资格保卫奥林匹斯山。 我差点把你加入那个名单。”",
    "guides my path as": "指引我的道路",
    "guides yours. Keep your distance if you choose, but we have the same goal. We can prove ourselves together.”": "指导你的。 如果你选择保持距离，但我们有相同的目标。 我们可以一起证明自己。”",
    "learns a new  ability:": "学习一项新能力：",
    "Road to Dodona - Mountain Opening": "通往多多纳的道路 - 开放的山口",
    "Sure Shot": "必杀技",
    "takes 3 damage from Sure Shot's effect.": "受到 必杀技 效果的 3 点伤害。",
    "takes 5 damage from Claw's effect.": "受到爪击效果的 5 点伤害。",
    "takes 5 damage from Sure Shot's effect.": "受到 必杀技 效果的 5 点伤害。",
    "The gods seem to each have their own favorites.": "诸神似乎各有各的喜好。",
    "Throwing Stones": "投掷石块",
    "uses Claw on": "使用爪",
    "uses Enrage.": "使用激怒。",
    "uses Sure Shot on": "使用 必杀技",
    "uses Wounding Arrow on": "使用致伤箭",
    "You find a treasure chest containing": "你找到一个宝箱，里面有",
    "You found a chest containing 30": "你找到了一个宝箱装有 30",
    "You reply with a grin.": "你笑着回答。",
    "Your opponent says, cautiously lowering her bow.": "你的对手说，小心地放下她的弓。",
    "Your power has grown significantly since you were chosen by": "自从被选为",
    "Zosime": "佐西美",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Mountain Opening": "开放的山口",
    "Road to Dodona - Delphi": "多多纳之路 - 德尔福",
    "Road to Dodona - Delphi Outskirts": "通往多多纳的道路 - 德尔斐郊区",
    "Road to Dodona": "通往多多纳的道路",
    "Delphi (Town)": "德尔福（镇）",
    "Delphi": "",
    "Athena": "雅典娜",
    "Bay": "海岸",
    "Aigosthena - Bay": "Aigosthena - 海岸",
    "Aigosthena": "艾格斯特纳",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "X": "X",
    "B": "B",
    "A": "A",
    "for": "",
    "For": "",
    "|": "|",
    "★": "★",
    "⇅": "⇅",
    "↪": "↪",
    "→": "→",
    "»": "»",
    "!": "!",
    "-": "-",
    "T": "T",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Water Serpent ": "水蛇 ",
    "Upper Coast (": "上海岸（",
    "Bay (": "海湾（",
    "Delphi Outskirts (": "德尔福郊外 (",
    "Average per hour: ": "平均每小时：",
    "damage.": "伤害。",
    "Assigned Followers: ": "分配的追随者：",
    "Coastal Roads of Locris (": "洛克里斯 的沿海道路 (",
    "Highwayman ": "拦路强盗 ",
    "Thief ": "窃贼 ",
    "Weapon - ": "武器 - ",
    "Countryside (": "乡村 (",
    "Bandit ": "土匪 ",
    "Coyote ": "土狼 ",
    "Mountain Opening (": "开放的山口（",
    "Incoming DPS: ": "受到的DPS：",
    "Party DPS: ": "队伍DPS：",
    "Red-Feathered Harpy ": "红羽鹰身女妖 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " wins)": " 获胜)",
    " win)": " 获胜)",
    "% of Attack": "% 攻击",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\(([\d\.]+):([\d\.]+):([\d\.]+)\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^\/ ([\d\.,]+)$/,
    /^ \/ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^\(Lv (.+) \- Ach (.+) Complete\)$/, '(等级 $1 - 成就完成 $2)'],
    [/^Deal (.+) damage to a target.$/, '对1个目标造成 $1 伤害。'],
    [/^gains (.+) HP from Divine Strike.$/, '从神圣打击中获得 $1 生命值。'],
    [/^damage to a single target (.+) times every$/, '对单个目标造成 $1 次伤害'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) Max HP$/, '\+$1 生命值上限'],
    [/^\+([\d\.,]+) Attack$/, '\+$1 攻击'],
    [/^\+([\d\.,]+) Agility$/, '\+$1 敏捷'],
    [/^\+([\d\.,]+) Luck$/, '\+$1 幸运'],
    [/^\+([\d\.,]+) Defense$/, '\+$1 防御'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) XP$/, '$1 经验'],
    [/^([\d\.,]+) Olive$/, '$1 橄榄'],
    [/^([\d\.,]+) Throwing Stone$/, '$1 飞石'],
    [/^([\d\.,]+) Coin$/, '$1 金币'],
    [/^([\d\.,]+) Attack$/, '$1 攻击'],
    [/^([\d\.,]+) Agility$/, '$1 敏捷'],
    [/^([\d\.,]+) Coins$/, '$1 金币'],
    [/^([\d\.,]+) Light Leathers$/, '$1 轻皮革'],
    [/^([\d\.,]+) Light Leather$/, '$1 轻皮革'],
    [/^([\d\.,]+) Max HP$/, '$1 生命上限'],
    [/^([\d\.,]+) more achievements needed$/, '还需要 $1 成就'],
    [/^\(([\d\.,]+) owned\)$/, '（拥有 $1）'],
    [/^of the damage dealt. ([\d\.,]+) second cooldown.$/, '造成的伤害。 $1 秒冷却时间。'],
    [/^Remaining Duration: ([\d\.,]+) seconds$/, '剩余时长：$1 秒'],
    [/^for ([\d\.,]+) damage.$/, '造成了 $1 伤害。'],
    [/^for ([\d\.,]+) damage as well.$/, '以及造成了 $1 伤害。'],
    [/^for ([\d\.,]+)$/, ' $1'],
    [/^Lv ([\d\.,]+)$/, '等级 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);